### PR TITLE
fix nullable bug at flutter 2.5.0

### LINKED ISSUE #28: Flutter 2.5 compatibility
After upgrading from flutter 2.2  to 2.5 i am facing this error .

../../../.pub-cache/hosted/pub.dartlang.org/network_to_file_image-3.0.0/lib/network_to_file_image.dart:313:34: Error: A value of type 'Future<bool> Function(Uri, String, String)?' can't be assigned to a variable of type 'Future<bool> Function(Uri, String, String?)?' because 'String?' is nullable and 'String' isn't.
 - 'Future' is from 'dart:async'.
 - 'Uri' is from 'dart:core'.
      _realClient.authenticate = f;

### PR DESCRIPTION
**Pull request by Ali1Ammar**
fix #28

### CODE REVIEW

**Comment by JaffaKetchup** [comment]
Thanks for the PR, please can @marcglasberg merge ASAP as this is a breaking issue?

**Review by marcglasberg — APPROVED** [review]

**Comment by JaffaKetchup** [comment]
Thanks! Any chance of a pub.dev release soon?

**Comment by marcglasberg** [comment]
@JaffaKetchup Could you please tell me if version `network_to_file_image: ^3.0.1` works for Flutter 2.5? I can't upgrade just now, so I'd appreciate if you could test and tell me.

**Comment by JaffaKetchup** [comment]
Hi,
The app does appear to build successfully now, and the caching does indeed work as expected.
Many thanks 👍 :)

**Pull request merged**
